### ISSUE TITLE
Display details of Reddits without images?

### ISSUE THREAD

**Issue by hollowaytyl** [marcelobusico/reddit-ios-app#1]
Very nice app, but what if I wanted to view details and not just an image? Or if I wanted to view the details of reddits that don't have images? 

What swift files would I need to change and how do I go about it?

Thanks!

**Comment by hollowaytyl** [comment]
I'm assuming that it's possible to pass the model. attributes used in the Reddit cell and pass them to the detail controller, but if that's correct - how do I access ever post regardless of image format?

**Comment by marcelobusico** [comment]
Thanks @hollowaytyl,

This is only an example application, intended only to demonstrate coding styles, patterns and processes. It is not mean to be a complete reddit reader. Feel free to fork this repository and add your favourite features there. 

Regards,
Marcelo.

**Comment by hollowaytyl** [comment]
Understood. Could you at least tell me whether or not there's a specific line in the project that explicitly tells the app to only go to the detail view when the image is a certain format? If it's there I'll find it. 

Thanks

**Comment by marcelobusico** [comment]
@hollowaytyl Sure, the filter is on the following class line:

https://github.com/marcelobusico/reddit-ios-app/blob/master/Reddit-App/Reddit-App/ServiceAdapters/RedditServiceAdapter.swift#L155

Regards,
Marcelo.
